name: form_builder_generator_annotation
description: Annotations for nameof package, that is Generator for  Dart class member's names, such as fields, properties, methods, constructors 
version: 0.1.1
homepage: https://github.com/flankb/nameof

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
