name: example
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  form_builder_generator_annotation:
    path: ../../form_builder_generator_annotation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  form_builder_generator:
    path: ..


dev_dependencies:
  lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner:
  form_builder_generator_dev:
    path: ../../form_builder_generator_dev
