name: example
description: Example for nameof package
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  nameof_annotation:
    path: ../../nameof_annotation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0


dev_dependencies:
  lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner:
  nameof:
    path: ..
